version: '2'
services:
    rabbit:
        image: 'rabbitmq:3.6.14'

    webserver:
        image: hubbabt/docker-airflow:1.8.2
        restart: always
        depends_on:
            - postgres
            - rabbit
        environment:
            - LOAD_EX=n
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            - POSTGRES_USER=USER
            - POSTGRES_PASSWORD=SECRET
            - POSTGRES_DB=URI
        volumes:
            - ./dags:/usr/local/airflow/dags
        ports:
            - "8080:8080"
        command: webserver

    flower:
        image: hubbabt/docker-airflow:1.8.2
        restart: always
        depends_on:
            - rabbit
        environment:
            - EXECUTOR=Celery
        ports:
            - "5555:5555"
        command: flower

    scheduler:
        image: hubbabt/docker-airflow:1.8.2
        restart: always
        depends_on:
            - webserver
        volumes:
            - ./dags:/usr/local/airflow/dags
        environment:
            - LOAD_EX=n
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
            - RABBIT_HOST=??
            - RABBIT_PORT=5672
        command: scheduler

    worker:
        image: hubbabt/docker-airflow:1.8.2
        restart: always
        depends_on:
            - scheduler
        volumes:
            - ./dags:/usr/local/airflow/dags
        environment:
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        command: worker
            
